model_name: 'UNet'
scheduler_name: 'LinearNoiseScheduler'

save_pt_dir: '_construct/weight/unet_0/pt'
save_onnx_dir: '_construct/weight/unet_0/onnx'

diffusion_params:
  num_timesteps : 1000
  beta_start : 0.0015
  beta_end : 0.0195

ldm_params:
  down_channels: [ 128, 256, 256, 256]
  mid_channels: [ 256, 256]
  down_sample: [ False, False, False ]
  attn_down : [True, True, True]
  time_emb_dim: 256
  norm_channels : 32
  num_heads : 16
  conv_out_channels : 128
  num_down_layers: 2
  num_mid_layers: 2
  num_up_layers: 2
  condition_config:
    digit_condition_config :
      num_classes : 10
      cond_drop_prob : 0.1

autoencoder_params:
  z_channels: 3
  codebook_size : 20
  down_channels : [32, 64, 128]
  mid_channels : [128, 128]
  down_sample : [True, True]
  attn_down : [False, False]
  norm_channels: 32
  num_heads: 16
  num_down_layers : 1
  num_mid_layers : 1
  num_up_layers : 1
